version: '3.3' # optional since v1.27.0
services:
  api:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - .:/server/app
  client:
    build: ./client
    depends_on:
      - api
    ports:
      - '3000:3000'
    volumes:
      - .:/client/app
